services:
  portfolio:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: portfolio
    env_file: ".env"
    labels:
      - traefik.enable=true
      - traefik.http.routers.portfolio.rule=Host(`portfolio.${DOMAIN}`)
      - traefik.http.routers.portfolio.entrypoints=websecure
      - traefik.http.routers.portfolio.tls=true
      - traefik.http.routers.portfolio.tls.certresolver=myresolver
    networks:
      - webgateway
    command: "npm run build && npm run serve"
    volumes:
      - ./:/app
    working_dir: /app
networks:
  webgateway:
    name: ${NETWORK}
    external: true